FROM alpine
ENV appDescription This app is a sample of using ENV instructions
ENV appName=env-demo
ENV note1="The First Note First" note2=The\ Second\ Note\ Second \
	note3="The Third Note Third"
ENV changeMe="Old Value"
CMD ["sh"]